polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('evaluation/<int:evaluation_id>', views.evaluation, name='evaluation'),
    path('start/<int:evaluation_id>', views.start, name='start'),
    path('total/<int:evaluation_id>', views.total, name='total'),
    path('question/<str:task_id>/<int:question_order>', views.question, name='question'),
    path('submit/<int:question_id>', views.submit, name='submit'),
    path('wave/<int:question_id>.wav', views.wave, name='wave'),
    path('result/<str:task_id>', views.result, name='result')
]

rabtest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('abtest/', include('abtest.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
from django.core.validators import MinValueValidator
import uuid

# Create your models here.

class Evaluation(models.Model):
    method_a = models.CharField(max_length=256)
    method_b = models.CharField(max_length=256)
    n_questions = models.PositiveSmallIntegerField(null=False, default=5, validators=[MinValueValidator(1)])
    n_data = models.PositiveSmallIntegerField(null=False, default=10, validators=[MinValueValidator(1)])

    def number_of_questions(self):
        return self.n_questions*2

class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    evaluation = models.ForeignKey(Evaluation, on_delete=models.CASCADE)

class Question(models.Model):
    order = models.PositiveSmallIntegerField(null=False, default=127, validators=[MinValueValidator(1)])
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    src_speaker = models.CharField(max_length=256)
    tgt_speaker = models.CharField(max_length=256)
    utterance = models.CharField(max_length=256)
    is_inverted = models.BooleanField(default=False)
    is_former_better = models.NullBooleanField()

polls/views.py
import pathlib
from io import BytesIO
from random import randint
import numpy as np
import scipy.io.wavfile as wavfile

from django.shortcuts import render, redirect
from django.http import HttpResponse, FileResponse
from django.template import loader

from .models import Evaluation, Task, Question

eval_root = pathlib.Path('/home/ubuntu/nn/data/eval')

def index(request):
    eval_list = Evaluation.objects.all()
    context = {
        'eval_list': eval_list
    }
    return render(request, 'polls/index.html', context)

def evaluation(request, evaluation_id):
    evaluation = Evaluation.objects.get(pk=evaluation_id)
    context = {
        'evaluation': evaluation
    }
    return render(request, 'polls/evaluation.html', context)

def random_comb(n):
    i = randint(1, n)
    j = randint(1, n-1)
    if j>=i:
        j += 1
    c = randint(0, 1)
    i = f"jvs{i+90:03}"
    j = f"jvs{j+90:03}"
    if c==0:
        return (i, j)
    else:
        return (j, i)

def start(request, evaluation_id):
    evaluation = Evaluation.objects.get(pk=evaluation_id)
    tgt_list = np.random.permutation(evaluation.n_data)[:evaluation.number_of_questions()//2]
    tgt_list = [(f"{i+91:03}.wav", *random_comb(10), randint(0, 1)==0) for i in tgt_list]
    tgt_list2 = [(*t[:3], not t[3]) for t in tgt_list]
    tgt_list = tgt_list + tgt_list2
    task = evaluation.task_set.create()
    for i in range(0, evaluation.number_of_questions()):
        q = task.question_set.create(
            order=i+1,
            src_speaker=tgt_list[i][1],
            tgt_speaker=tgt_list[i][2],
            utterance=tgt_list[i][0],
            is_inverted=tgt_list[i][3])

    return redirect('polls:question', task_id=task.id, question_order=1)

def question(request, task_id, question_order):
    question = Question.objects.filter(task__pk=task_id, order=question_order)[0]
    context = {
        'question': question
    }
    return render(request, 'polls/question.html', context)

def wave(request, question_id):
    question = Question.objects.get(pk=question_id)
    src_speaker = question.src_speaker
    tgt_speaker = question.tgt_speaker
    utterance = question.utterance

    method_A = question.task.evaluation.method_a
    method_B = question.task.evaluation.method_b
    if question.is_inverted:
        t = method_A
        method_A = method_B
        method_B = t

    ref_path = eval_root/method_A/tgt_speaker/'ref.wav'
    wave_A_path = eval_root/method_A/tgt_speaker/src_speaker/utterance
    wave_B_path = eval_root/method_B/tgt_speaker/src_speaker/utterance

    sr, ref = wavfile.read(ref_path)
    _, waveA = wavfile.read(wave_A_path)
    _, waveB = wavfile.read(wave_B_path)
    wave = np.hstack((ref, waveA, waveB))
    byte = BytesIO()
    wavfile.write(byte, sr, wave)
    byte.seek(0)

    return FileResponse(byte, filename="wave.wav")


def submit(request, question_id):
    is_a = True if request.POST['is_a'] == 'A' else False if request.POST['is_a'] == 'B' else None
    question = Question.objects.get(pk=question_id)
    question.is_former_better = is_a ^ question.is_inverted
    question.save()
    task = question.task
    evaluation = task.evaluation
    if question.order == evaluation.number_of_questions():
        return redirect('polls:result', task_id=task.id)
    else:
        return redirect('polls:question', task_id=task.id, question_order=question.order+1)

def result(request, task_id):
    task = Task.objects.get(pk=task_id)
    questions = task.question_set.all()
    valid = all([q.is_former_better is not None for q in questions])
    first_q = None
    for q in questions:
        if q.is_former_better is None:
            first_q = q
            break
    context = {
        'questions': questions,
        'valid': first_q is None,
        'first_q': first_q
    }
    return render(request, 'polls/result.html', context)

def total(request, evaluation_id):
    evaluation = Evaluation.objects.get(pk=evaluation_id)
    a = 0
    b = 0
    for t in evaluation.task_set.all():
        a += t.question_set.filter(is_former_better__exact=True).count()
        b += t.question_set.filter(is_former_better__exact=False).count()
    context = {
        "method_a": evaluation.method_a,
        "method_b": evaluation.method_b,
        "count_a": a,
        "count_b": b
    }
    return render(request, 'polls/total.html', context)

polls/templates/polls/evaluation.html
{% if evaluation %}
<div>
    <p>
        ある自然音声と、人工的に変換された2つの音声を聴き、どちらの音声が自然音声の話者性に近いかを答えていただきます。
    </p>
    <p>全部で{{evaluation.number_of_questions}}問あります。</p>
    <a href="{% url 'polls:start' evaluation.id %}">開始</a>
</div>
{% else %}
    <p>課題が見つかりません</p>
{% endif %}

polls/templates/polls/index.html
{% if eval_list %}
    <ul>
        {% for evaluation in eval_list %}
            <li><a href="{% url 'polls:total' evaluation.id %}">{{ evaluation.method_a }} | {{ evaluation.method_b }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>課題がありません。</p>
{% endif %}

polls/templates/polls/question.html
<h2>{{question.order}}/{{question.task.evaluation.number_of_questions}}</h2>
<div>
    <p>再生ボタンを押すと、ある人（参照話者）の音声のあと、人工的に合成された音声が2回再生されます。</p>
    <p>人工的に合成された音声のうち、どちらの話者性（声の響き）が参照話者に近いかを答えてください。</p>
</div>
<hr>
<audio
    id="wave"
    onended="onEnded();"
>
    <source src="{% url 'polls:wave' question.id %}">
</audio>
<div>
    <button onclick="play();">再生</button>
    <form action="{% url 'polls:submit' question.id %}" method="post">
        {% csrf_token %}
        <button disabled=true id="buttonA" type=submit name="is_a" value=A>前のほうが参照話者に近い</button>
        <button disabled=true id="buttonB" type=submit name="is_a" value=B>後のほうが参照話者に近い</button>
    </form>
</div>
<script type="text/javascript">
    function play(){
        document.getElementById('wave').play();
    }
    function onEnded(){
        document.getElementById('buttonA').disabled=false;
        document.getElementById('buttonB').disabled=false;
    }
</script>

polls/templates/polls/result.html
{% if valid %}
    <div>
        <p>お疲れさまでした。</p>
        <p>以下のテキストを提出してください。</p>
    </div>
    <hr>
    <div>
    {% for question in questions %}
        <p>
            {{question.task.id}}, {{question.id}}, {{question.is_former_better}}
        </p>
    {% endfor %}
    </div>
{% else %}
    <p>何らかの原因により、提出されていない回答があります。</p>
    <p>お手数ですが以下のリンクから再開してください。</p>
    <a href="{% url 'polls:question' first_q.task.id first_q.order %}">再開</a>
{% endif %}